name: .NET Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: PluginNetAtmo

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      #uses: microsoft/setup-msbuild@v1.1.1
      
    # Setup NuGet 
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
    - run: nuget restore $env:Solution_Name.sln

    # Build solution
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:platform=$env:Platforms
      env:
        Platforms: x86|x64
        Configuration: ${{ matrix.configuration }}
