name: .NET Build Debug x64

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]
        platforms: [x64]

    runs-on: windows-latest
    
    env:
      Solution_Name: PluginNetAtmo

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    # Setup NuGet 
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    # NuGet Restore 
    - name: NuGet Restore packages
      run: nuget restore $($env:Solution_Name + ".sln")

    # Build solution
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:platform=$env:Platforms
      env:
        Platforms: ${{ matrix.platforms }}
        Configuration: ${{ matrix.configuration }}
        
    # Copy artifact files
    - name: Copy artifact files
      run: mkdir PluginNetAtmo-$env:Platforms-$env:Configuration && copy PluginNetAtmo\obj\$env:Platforms\$env:Configuration\*.dll PluginNetAtmo-$env:Platforms-$env:Configuration && copy PluginNetAtmo\obj\$env:Platforms\$env:Configuration\*.pdb PluginNetAtmo-$env:Platforms-$env:Configuration
      env:
          Platforms: ${{ matrix.platforms }}
          Configuration: ${{ matrix.configuration }}
          
    # Prepare artifact for download    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PluginNetAtmo-${{ matrix.configuration }}-${{ matrix.platforms }}-${GITHUB_SHA::6}.dll
        # A file, directory or wildcard pattern that describes what to upload
        path:  |
          PluginNetAtmo\obj\$env:Platforms\$env:Configuration\*.dll
          PluginNetAtmo\obj\$env:Platforms\$env:Configuration\*.pdb
        retention-days: 5
      env:
        Platforms: ${{ matrix.platforms }}
        Configuration: ${{ matrix.configuration }}
